---
ID: "5db86cf4-855b-407b-9e8a-d7f825a88cbd"
Parent: "14197fff-2867-4e5e-a12a-320bead9ede3"
Template: "14197fff-2867-4e5e-a12a-320bead9ede3"
Path: /sitecore/templates/Foundation/Presentation/Rendering Settings/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{4E2DC2E5-59D3-40A2-B5DF-713D0425330D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181111T095021Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
