---
ID: "1e140398-7ea0-46ec-8a0e-f9073a2b8133"
Parent: "01597ce3-e846-4470-aee5-893704aee939"
Template: "545ac02c-7442-485e-90ed-5aa44171dfd7"
Path: /sitecore/content/Websites/Sitecore8Helix/Home/Products
DB: master
SharedFields:
- ID: "9aacf0e5-4c54-42e4-b7e1-16311390d70d"
  Hint: Facets
  Type: Multilist
  Value: |
    {558A0DBE-38E6-481A-B368-308078F48679}
    {E4F04C22-B0F0-4406-B0C0-D94190ED50B7}
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{40542DC8-0541-42EF-8876-67F53A104B0A}">
          <p:d />
        </r>
        <r
          uid="{A407A99E-0EA3-484B-AE62-0FCBED78D33D}"
          s:id="{DF16920A-B956-42FF-BE41-516A1793DE17}"
          s:ph="main" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180812T185710Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
