---
ID: "bb6b1a16-10ab-435b-810b-657f95d44c30"
Parent: "4be917af-f7bf-4a73-963e-a65b0ae57e84"
Template: "4be917af-f7bf-4a73-963e-a65b0ae57e84"
Path: /sitecore/templates/Foundation/Presentation/ParametersTemplate_RenderingType/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181111T105540Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
