---
ID: "bc0042df-6987-4949-a1cc-f9df2fedc8fd"
Parent: "6e4437fb-a51f-462f-bdbc-a88625961225"
Template: "6e4437fb-a51f-462f-bdbc-a88625961225"
Path: /sitecore/templates/Project/Sitecore8Helix/Page Types/Stores/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{A5A6B8FC-8D69-4B53-ABA6-C37546451E0C}">
        <r
          id="{CFC95028-B5A9-426B-A05D-966E70368FD2}"
          ph="main"
          uid="{1905DB72-14E9-48B2-B5E7-11A231433962}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181031T203708Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
