---
ID: "cce9bb87-2a62-4ee2-84f4-b00ea445985c"
Parent: "a2e86b79-c002-4c36-b85f-c8a8a95992f1"
Template: "a2e86b79-c002-4c36-b85f-c8a8a95992f1"
Path: /sitecore/templates/Project/Product/__Standard Values
DB: master
SharedFields:
- ID: "39c4902e-9960-4469-aeef-e878e9c8218f"
  Hint: __Hidden
  Type: Checkbox
  Value: 0
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
- ID: "d312103c-b36c-4ca5-864a-c85f9abda503"
  Hint: __Is Bucket
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "053ee4b8-cdb1-4bc7-a516-0820f6e1feaf"
      Hint: Product Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180812T152443Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
