---
ID: "84515380-db0c-4cc9-b32f-d6c8b9ff5f58"
Parent: "545ac02c-7442-485e-90ed-5aa44171dfd7"
Template: "545ac02c-7442-485e-90ed-5aa44171dfd7"
Path: /sitecore/templates/Project/Sitecore8Helix/Page Types/Products/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{A5A6B8FC-8D69-4B53-ABA6-C37546451E0C}">
        <r
          id="{DF16920A-B956-42FF-BE41-516A1793DE17}"
          ph="main"
          uid="{40542DC8-0541-42EF-8876-67F53A104B0A}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181031T203741Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
