---
ID: "21fd5d49-db58-49c7-a37f-ef94b6d7b0b0"
Parent: "2764b5f0-1398-462f-9609-aa7e7e20ef7f"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Feature/Products/_ProductContent/Content/Product Description
DB: master
SharedFields:
- ID: "39c4902e-9960-4469-aeef-e878e9c8218f"
  Hint: __Hidden
  Type: Checkbox
  Value: 0
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Multi-Line Text"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
- ID: "d312103c-b36c-4ca5-864a-c85f9abda503"
  Hint: __Is Bucket
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180812T152431Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
