---
ID: "053ee4b8-cdb1-4bc7-a516-0820f6e1feaf"
Parent: "122c8157-63a9-4256-b676-eb7a6116c3e8"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Feature/Products/Product/Content/Product Title
DB: master
SharedFields:
- ID: "39c4902e-9960-4469-aeef-e878e9c8218f"
  Hint: __Hidden
  Type: Checkbox
  Value: 0
- ID: "93d1b217-b8f4-462e-babf-68298c9ce667"
  Hint: __Boost
  Value: 
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Single-Line Text"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
- ID: "d312103c-b36c-4ca5-864a-c85f9abda503"
  Hint: __Is Bucket
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180812T152431Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
